#!/bin/bash

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "./docker-export-mysql [DATABASE] [FILEPATH] [CLEAN (optional)]"

elif [ "$1" ] && [ "$2" ] && [ -z "$3" ]; then
    mysqldump -u root -p1234  "$1" -h 0.0.0.0 --port=3307 > "$2"

elif [ "$1" ] && [ "$2" ] && [ "$3" ]; then 
    mysqldump -u root -p1234  "$1" --add-drop-database -B -h 0.0.0.0 --port=3307 > "$2"
fi